web/src/Entity/FreshUser.php
<?php

namespace App\Entity;

use App\Repository\FreshUserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: FreshUserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class FreshUser implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var ?string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\Column(length: 255)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $registerDate = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $lastConnection = null;

    #[ORM\OneToMany(mappedBy: 'owner', targetEntity: Refrigerator::class, orphanRemoval: true)]
    private Collection $refrigerators;

    #[ORM\OneToMany(mappedBy: 'recipient', targetEntity: Alert::class, orphanRemoval: true)]
    private Collection $alerts;

    #[ORM\OneToMany(mappedBy: 'owner', targetEntity: Recipe::class, orphanRemoval: true)]
    private Collection $recipes;

    public function __construct()
    {
        $this->refrigerators = new ArrayCollection();
        $this->alerts = new ArrayCollection();
        $this->recipes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string)$this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getRegisterDate(): ?\DateTimeInterface
    {
        return $this->registerDate;
    }

    public function setRegisterDate(\DateTimeInterface $register_date): static
    {
        $this->registerDate = $register_date;

        return $this;
    }

    public function getLastConnection(): ?\DateTimeInterface
    {
        return $this->lastConnection;
    }

    public function setLastConnection(\DateTimeInterface $last_connection): static
    {
        $this->lastConnection = $last_connection;

        return $this;
    }

    /**
     * @return Collection<int, Refrigerator>
     */
    public function getRefrigerators(): Collection
    {
        return $this->refrigerators;
    }

    public function addRefrigerator(Refrigerator $refrigerator): static
    {
        if (!$this->refrigerators->contains($refrigerator)) {
            $this->refrigerators->add($refrigerator);
            $refrigerator->setOwner($this);
        }

        return $this;
    }

    public function removeRefrigerator(Refrigerator $refrigerator): static
    {
        if ($this->refrigerators->removeElement($refrigerator)) {
            // set the owning side to null (unless already changed)
            if ($refrigerator->getOwner() === $this) {
                $refrigerator->setOwner(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Alert>
     */
    public function getAlerts(): Collection
    {
        return $this->alerts;
    }

    public function addAlert(Alert $alert): static
    {
        if (!$this->alerts->contains($alert)) {
            $this->alerts->add($alert);
            $alert->setRecipient($this);
        }

        return $this;
    }

    public function removeAlert(Alert $alert): static
    {
        if ($this->alerts->removeElement($alert)) {
            // set the owning side to null (unless already changed)
            if ($alert->getRecipient() === $this) {
                $alert->setRecipient(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Recipe>
     */
    public function getRecipes(): Collection
    {
        return $this->recipes;
    }

    public function addRecipe(Recipe $recipe): static
    {
        if (!$this->recipes->contains($recipe)) {
            $this->recipes->add($recipe);
            $recipe->setOwner($this);
        }

        return $this;
    }

    public function removeRecipe(Recipe $recipe): static
    {
        if ($this->recipes->removeElement($recipe)) {
            // set the owning side to null (unless already changed)
            if ($recipe->getOwner() === $this) {
                $recipe->setOwner(null);
            }
        }

        return $this;
    }
}

web/templates/account.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fresh !{% endblock %}

{% block body %}
    <div class="text-center">

        <h1 class="font-bold text-3xl mb-5">{{ user.firstName }} voici vos informations</h1>

        {% if user.verified %}
            <div class="flex justify-center m-5">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-question-circle" viewBox="0 0 16 16">
                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"/>
                    <path d="M5.255 5.786a.237.237 0 0 0 .241.247h.825c.138 0 .248-.113.266-.25.09-.656.54-1.134 1.342-1.134.686 0 1.314.343 1.314 1.168 0 .635-.374.927-.965 1.371-.673.489-1.206 1.06-1.168 1.987l.003.217a.25.25 0 0 0 .25.246h.811a.25.25 0 0 0 .25-.25v-.105c0-.718.273-.927 1.01-1.486.609-.463 1.244-.977 1.244-2.056 0-1.511-1.276-2.241-2.673-2.241-1.267 0-2.655.59-2.75 2.286m1.557 5.763c0 .533.425.927 1.01.927.609 0 1.028-.394 1.028-.927 0-.552-.42-.94-1.029-.94-.584 0-1.009.388-1.009.94"/>
                </svg>
                <p class="mt-2 bg-pink-500 text-white rounded-2xl p-2 w-5/12">Votre compte est vérifié !</p>
            </div>
        {% else %}
            <div class="flex justify-center m-5">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-exclamation-triangle" viewBox="0 0 16 16">
                    <path d="M7.938 2.016A.13.13 0 0 1 8.002 2a.13.13 0 0 1 .063.016.15.15 0 0 1 .054.057l6.857 11.667c.036.06.035.124.002.183a.2.2 0 0 1-.054.06.1.1 0 0 1-.066.017H1.146a.1.1 0 0 1-.066-.017.2.2 0 0 1-.054-.06.18.18 0 0 1 .002-.183L7.884 2.073a.15.15 0 0 1 .054-.057m1.044-.45a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767z"/>
                    <path d="M7.002 12a1 1 0 1 1 2 0 1 1 0 0 1-2 0M7.1 5.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0z"/>
                </svg>
                <p class="mt-2 bg-error text-white rounded-2xl p-2 w-5/12">Votre compte n'est pas vérifié ! <a
                            href="{{ path('app_resend_registration_confirmation_email') }}"
                            class="btn btn-primary border-success text-white">
                        <button>RENVOYER UN MAIL DE VÉRIFICATION</button>
                    </a></p>
            </div>
        {% endif %}
        {{ form_errors(formUser) }}

        {% if modify is defined %}

            {{ form_start(formUser) }}
            {{ form_row(formUser.email) }}
            {{ form_row(formUser.firstname) }}
            {{ form_row(formUser.name) }}
            {{ form_row(formUser.plainPassword) }}
            <p>Vous avez accepté les conditions d'utilisations. <a class="link" href="#">Voir les conditions</a></p><br>

            <button type="submit" class="btn btn-lg btn-primary mt-5 mb-5 text-white">ENREGISTRER</button>
            {{ form_end(formUser) }}
        {% else %}
            {{ form_start(formUser) }}
            {{ form_row(formUser.email,{'attr':{'disabled':'true'}}) }}
            {{ form_row(formUser.firstname,{'attr':{'disabled':'true'}}) }}
            {{ form_row(formUser.name,{'attr':{'disabled':'true'}}) }}
            {{ form_row(formUser.plainPassword,{'attr':{'disabled':'true'}}) }}
            <p>Vous avez accepté les conditions d'utilisations. <a class="link" href="#">Voir les conditions</a></p><br>
            <input hidden name="modify" value="true">
            <button type="submit" class="btn btn-lg btn-warning text-white mt-5 mb-5">MODIFIER</button>
            {{ form_end(formUser) }}

        {% endif %}
        {{ form_end(formUser) }}

        <a href="#" class="btn btn-error text-white" onclick="coming_soon.showModal();">SUPPRIMER DÉFINITIVEMENT MON
            COMPTE</a><br>
        <a href="{{ path('app_main') }}" class="btn btn-info text-white mt-5">
            <button><< RETOUR</button>
        </a>

        <dialog id="coming_soon" class="modal">
            <div class="modal-box bg-white">
                <h3 class="font-bold text-xl">{{ user.firstname }}, cette action est bientôt disponible...</b></h3>
                <div class="flex justify-center mt-2">
                    <a href="{{ path('app_fresh_account') }}" class="btn btn-info text-white text-center">FERMER</a>
                </div>
            </div>
        </dialog>
    </div>
{% endblock %}

web/templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Fresh !{% endblock %}</title>
    <link rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
    {% block stylesheets %}
        {{ encore_entry_link_tags('app') }}
    {% endblock %}

    {% block javascripts %}
        {{ encore_entry_script_tags('app') }}
    {% endblock %}
</head>
<body class="theme-mytheme bg-white">
<header>
    {% for label, flashes in app.session.flashbag.all %}
    {% set i = 0 %}
    {% for flash in flashes %}
    {% if label == "error" %}
    <div class="alert text-white" id="flash-{{ i }}" style="background-color: #c0392b">
        {% elseif label == "warning" %}
        <div class="alert text-white" id="flash-{{ i }}" style="background-color: #e67e22">
            {% else %}
            <div class="alert bg-{{ label }} text-white" id="flash-{{ i }}">
                {% endif %}
                {{ flash|raw }}
            </div>
            <script>
                setTimeout(function () {
                    document.getElementById('flash-{{ i }}').style = "display:none;";
                }, 5000);
            </script>
            {% set i = i+1 %}
            {% endfor %}
            {% endfor %}

            <nav class="px-4 lg:px-6 py-2.5">
                <div class="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl">
                    <a href="{{ path('app_main') }}" class="flex items-center">
                        <h1 class="self-center text-7xl italic font-bold text-success">Fresh !</h1>
                    </a>
                    {% if app.user %}
                        <div class="flex items-center lg:order-2">
                            <a href="{{ path('app_fresh_account') }}" class="m-7 btn bg-white border-gray-500">
                                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor"
                                     class="bi bi-person-circle" viewBox="0 0 16 16">
                                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                                    <path fill-rule="evenodd"
                                          d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
                                </svg>
                            </a>
                            <a href="{{ path('app_logout') }}" class="text-white font-bold">
                                <div class="bg-success border-2 border-primary btn text-white">
                                    DÉCONNEXION
                                </div>
                            </a>
                        </div>
                    {% endif %}
                </div>
            </nav>
</header>
{% block body %}{% endblock %}
</body>
</html>

web/templates/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% if app.user.verified == false %}
        <div class="alert alert-warning font-bold text-white text-center flex justify-center rounded-none">
            <p>Vous devez activer votre compte en cliquant sur le lien envoyé par mail ! (no-reply@fresh.app)</p>
            <a href="{{ path('app_resend_registration_confirmation_email') }}"
               class="btn btn-primary border-success text-white">Cliquez pour renvoyer un lien
                d'activation</a>
        </div>
    {% else %}
        <div class="text-center">
            <h1 class="font-bold text-3xl">Bonjour {{ user.firstname }},</h1>
            <script>
                function closeAlert() {
                    for (let e in document.getElementsByClassName('freshalert')) {
                        document.getElementsByClassName('freshalert').item(e).hidden = true;
                    }
                    document.getElementById("btn-show-alert").classList.remove("hidden");
                    document.getElementById("btn-show-alert").classList.add("flex");
                    document.getElementById("btn-hide-alert").classList.remove("flex");
                    document.getElementById("btn-hide-alert").classList.add("hidden");
                }

                function openAlert() {
                    for (let e in document.getElementsByClassName('freshalert')) {
                        document.getElementsByClassName('freshalert').item(e).hidden = false;
                    }
                    document.getElementById("btn-show-alert").classList.remove("flex");
                    document.getElementById("btn-show-alert").classList.add("hidden");
                    document.getElementById("btn-hide-alert").classList.remove("hidden");
                    document.getElementById("btn-hide-alert").classList.add("flex");
                }
            </script>
            {% if alerts|length > 0 %}
                {% set legacyAlertString = "alerte" %}
                {% if alerts|length > 1 %}
                    {% set legacyAlertString = "alertes" %}
                {% endif %}
                <p>Vous avez {{ alerts|length ~ " " ~ legacyAlertString }} !</p>
                <div class="flex justify-center text-center">
                    <button class="bg-pink-500 rounded text-white p-2 font-bold justify-around text-center"
                            onclick="closeAlert()" id="btn-hide-alert">CACHER LES ALERTES
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-eye-slash" viewBox="0 0 16 16">
                            <path d="M13.359 11.238C15.06 9.72 16 8 16 8s-3-5.5-8-5.5a7 7 0 0 0-2.79.588l.77.771A6 6 0 0 1 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13 13 0 0 1 14.828 8q-.086.13-.195.288c-.335.48-.83 1.12-1.465 1.755q-.247.248-.517.486z"/>
                            <path d="M11.297 9.176a3.5 3.5 0 0 0-4.474-4.474l.823.823a2.5 2.5 0 0 1 2.829 2.829zm-2.943 1.299.822.822a3.5 3.5 0 0 1-4.474-4.474l.823.823a2.5 2.5 0 0 0 2.829 2.829"/>
                            <path d="M3.35 5.47q-.27.24-.518.487A13 13 0 0 0 1.172 8l.195.288c.335.48.83 1.12 1.465 1.755C4.121 11.332 5.881 12.5 8 12.5c.716 0 1.39-.133 2.02-.36l.77.772A7 7 0 0 1 8 13.5C3 13.5 0 8 0 8s.939-1.721 2.641-3.238l.708.709zm10.296 8.884-12-12 .708-.708 12 12z"/>
                        </svg>
                    </button>
                    <button class="bg-pink-500 rounded text-white p-2 font-bold justify-around text-center hidden"
                            onclick="openAlert()" id="btn-show-alert">MONTRER LES ALERTES
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-eye" viewBox="0 0 16 16">
                            <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8M1.173 8a13 13 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5s3.879 1.168 5.168 2.457A13 13 0 0 1 14.828 8q-.086.13-.195.288c-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5s-3.879-1.168-5.168-2.457A13 13 0 0 1 1.172 8z"/>
                            <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0"/>
                        </svg>
                    </button>
                </div>
                <div class="space h-2"></div>
                {% set i = 0 %}
                {# ... #}
                {% for alert in alerts %}
                <div id="alert-{{ i }}"
                     class="freshalert text-white px-6 py-4 border-0 rounded relative mb-2 bg-pink-500">
                        <span class="inline-block align-middle mr-8">
                            <b class="capitalize">{{ alert.food.name }}</b> se trouvant dans <b
                                    class="capitalize">{{ alert.refrigerator.name }}</b><br>
                            <b class="capitalize">Quantité : {{ alert.food.quantity }}</b><br>
                            {{ alert.message }}
                        </span>
                </div>
                <script>
                    setTimeout(function () {
                        closeAlert();
                    }, 10000);
                </script>
                {% set i = i+1 %}
                {% endfor %}
                {# ... #}
            {% else %}
                <p>Aucune alerte, c'est bon signe !</p>
            {% endif %}
        </div>
        <div class="space h-20"></div>
        <h2 class="text-center bold text-2xl">Vos frigos</h2>
        <div class="space h-5"></div>
        {% if user.refrigerators|length == 0 %}
            <div class="text-center">
                <p>Vous n'avez pas de frigo, donc pas d'aliments !</p>
            </div>
        {% endif %}
        <div class="text-center flex justify-around p-4"
             style="background-image: url('{{ asset('img/IMG_2619.jpg') }}');background-size: cover;">
            {% if user.refrigerators|length < 3 %}
                {% set number = 0 %}
                {% for refrigerator in user.refrigerators %}
                    {% set number=number+1 %}
                    <div>
                        <a href="{{ path('app_refrigerator',{'number':number}) }}"
                           class="text-center font-bold capitalize" style="opacity: 0.99;">
                            <img src="{{ asset('img/_fc63166d-6d43-4a34-a186-eb67efa4d00d.jpg') }}" alt="Frigo"
                                 height="512px" width="512px">
                            <span class="badge bg-white">{{ refrigerator.name }}</span>
                        </a>
                    </div>
                {% endfor %}
                {% if user.refrigerators|length != 2 %}
                    <a href="{{ path('app_refrigerator_add') }}" class="font-semibold capitalize m-10">
                        <div class="bg-primary rounded-2xl text-white p-10 h-full w-full flex items-center justify-center">
                            + AJOUTER UN FRIGO
                        </div>
                    </a>
                {% endif %}
            {% endif %}
        </div>
        <h2 class="text-center bold text-2xl mt-5">Vos recettes</h2>
        <div class="space h-5"></div>
        {% if user.recipes|length == 0 %}
            <div class="text-center">
                <p>Vous n'avez pas de recettes :'(</p>
            </div>
        {% endif %}
        <div class="w-full" style="background-image: url('{{ asset('img/IMG_2620.png') }}');background-size: cover;">
            <div class="text-center flex justify-center">
                {% set number = 0 %}
                <div class="grid grid-cols-4 gap-4 m-2">
                    {% for recipe in user.recipes %}
                        {% set number=number+1 %}
                        <div>
                            <a href="{{ path('app_recipe',{'number':number}) }}"
                               class="text-center font-bold capitalize">
                                <img src="{{ asset('img/_c29e01f8-d811-4281-8513-79172f6bc93f.jpg') }}" alt="Frigo"
                                     height="512px" width="512px">
                                <span class="badge bg-white">{{ recipe.name }}</span>
                            </a>
                        </div>
                    {% endfor %}
                    {% if user.recipes|length < 10 %}
                        <a href="{{ path('app_recipe_add') }}" class="font-semibold capitalize m-10">
                            <div class="bg-primary rounded-2xl text-white p-10 h-full w-full flex items-center justify-center">
                                + AJOUTER UNE RECETTE
                            </div>
                        </a>
                    {% else %}
                        <span class="badge badge-error text-white">Vous ne pouvez pas rajouter plus de 10 recettes.</span>
                    {% endif %}
                </div>
            </div>
        </div>
    {% endif %}
    {% set number = 1 %}
{% endblock %}

web/templates/recovery-password.html.twig
{% extends 'base.html.twig' %}

{% block title %} Fresh !{% endblock %}

{% block body %}
    <div class="text-center">
        {% if email is defined %}
            <h1>Envoyer un e-mail pour retrouver votre mot de passe !</h1>

            <form action="{{ path('app_recovery_password') }}" class="mt-5" method="post">
                <label for="email">Votre e-mail : </label>
                <input type="email" value="{{ email }}" name="email" class="input bg-white border-gray-500 rounded"><br>
                <input hidden name="_send_email_token" value="{{ csrf_token('_send_email_token_value') }}">
                <button type="submit" class="btn btn-success text-white mt-5">ENVOYER !</button>
            </form>
        {% elseif token is defined %}
            <h1 class="font-bold text-3xl mb-5">Modification de mot de passe</h1>

            <form action="{{ path('app_recovery_password') }}" method="post">
                <input type="password" name="plain-password">
                <input type="password" name="valid-password">
                <input hidden name="_valid_modify_password_{{ user.id }}"
                       value="{{ csrf_token('_valid_modify_password_'~ user.id ~'_token') }}">
                <input hidden name="user_id" value="{{ user.id }}">
                <button type="submit" class="btn btn-lg btn-primary mt-5 mb-5">MODIFIER !</button>
            </form>
        {% endif %}
    </div>
{% endblock %}